name: 🐛 Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for reporting a bug! Please fill out this template to help us fix it quickly.

              💡 **How to find versions:**
              - **Plugin version**: Settings → Community plugins → find your plugin
              - **Obsidian version**: Settings → About → App version

    - type: textarea
      id: description
      attributes:
          label: 🔍 Bug Description
          description: Clear description of what went wrong
          placeholder: The plugin crashes when I try to search for movies...
      validations:
          required: true

    - type: dropdown
      id: obsidian-version
      attributes:
          label: 📱 Obsidian Version
          description: "If your version is not listed, select 'Other' and specify in the field below"
          options:
              - v1.8.10 (latest)
              - v1.8.9
              - v1.8.7
              - v1.8.4
              - v1.8.3
              - v1.7.7
              - v1.7.6
              - v1.7.5
              - v1.7.4
              - v1.6.7
              - Other version (specify below)
      validations:
          required: true

    - type: input
      id: obsidian-version-other
      attributes:
          label: 🔧 Other Obsidian Version
          description: "Only fill this if you selected 'Other version' above. Use format: v1.2.3 or 1.2.3"
          placeholder: "Example: v1.8.11 or 1.8.11"

    - type: dropdown
      id: plugin-version
      attributes:
          label: 🔌 Plugin Version
          description: "Check in Settings → Community plugins. If not listed, select 'Other' and specify below"
          options:
              - v2.0.0 (latest)
              - v1.0.0
              - v0.1.0
              - Other version (specify below)
      validations:
          required: true

    - type: input
      id: plugin-version-other
      attributes:
          label: 🔧 Other Plugin Version
          description: "Only fill this if you selected 'Other version' above. Use format: v0.1.2 or 0.1.2"
          placeholder: "Example: v0.1.1 or 0.1.1"

    - type: dropdown
      id: os
      attributes:
          label: 💻 Operating System
          options:
              - Windows
              - macOS
              - Linux
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: 🔄 Steps to Reproduce
          description: Step by step instructions
          placeholder: |
              1. Open plugin
              2. Search for "Matrix"
              3. Click first result
              4. Error appears
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: ✅ Expected Behavior
          placeholder: Should create a note with movie info...
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: ❌ Actual Behavior
          placeholder: Instead, got error message...
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: 📋 Additional Info
          description: Console errors, screenshots, template used, etc.
          placeholder: |
              - Using custom template
              - Console error: [paste here]
              - Screenshot: [attach if helpful]
